"""initial_schema

Revision ID: 4acb28a9ff2a
Revises: 
Create Date: 2026-09-23 12:47:25.858596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acb28a9ff2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('berth_preference', sa.String(length=20), nullable=True),
    sa.Column('id_type', sa.String(length=30), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_id'), 'passengers', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('seat_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_seat_classes_id'), 'seat_classes', ['id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_city'), 'stations', ['city'], unique=False)
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_station_id', sa.Integer(), nullable=False),
    sa.Column('destination_station_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.String(length=10), nullable=False),
    sa.Column('arrival_time', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('running_days', sa.String(length=50), nullable=False),
    sa.Column('train_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['source_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_name'), 'trains', ['name'], unique=False)
    op.create_index(op.f('ix_trains_number'), 'trains', ['number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('booked_seats', sa.Integer(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('rac_seats', sa.Integer(), nullable=True),
    sa.Column('waiting_list', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['seat_classes.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'journey_date', 'class_id', name='uq_train_date_class')
    )
    op.create_index(op.f('ix_availability_id'), 'availability', ['id'], unique=False)
    op.create_index(op.f('ix_availability_journey_date'), 'availability', ['journey_date'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('total_fare', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['seat_classes.id'], ),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_journey_date'), 'bookings', ['journey_date'], unique=False)
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('coach_number', sa.String(length=10), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['seat_classes.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_id'), 'coaches', ['id'], unique=False)
    op.create_table('fares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('reservation_charge', sa.Float(), nullable=True),
    sa.Column('superfast_charge', sa.Float(), nullable=True),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('total_fare', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['seat_classes.id'], ),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fares_id'), 'fares', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('train_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_routes_id'), 'train_routes', ['id'], unique=False)
    op.create_table('train_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(length=10), nullable=False),
    sa.Column('departure_time', sa.String(length=10), nullable=False),
    sa.Column('halt_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_from_origin_km', sa.Float(), nullable=True),
    sa.Column('day_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'stop_number', name='uq_train_stop_number')
    )
    op.create_index(op.f('ix_train_stops_id'), 'train_stops', ['id'], unique=False)
    op.create_table('booking_passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('coach_number', sa.String(length=10), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('berth_type', sa.String(length=20), nullable=True),
    sa.Column('booking_status', sa.String(length=20), nullable=True),
    sa.Column('current_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_passengers_id'), 'booking_passengers', ['id'], unique=False)
    op.create_table('cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancellation_reference', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_passengers_count', sa.Integer(), nullable=False),
    sa.Column('cancellation_fee', sa.Float(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancellations_cancellation_reference'), 'cancellations', ['cancellation_reference'], unique=True)
    op.create_index(op.f('ix_cancellations_id'), 'cancellations', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_table('pnr_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnr_number', sa.String(length=10), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnr_records_id'), 'pnr_records', ['id'], unique=False)
    op.create_index(op.f('ix_pnr_records_pnr_number'), 'pnr_records', ['pnr_number'], unique=True)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('berth_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'seat_number', name='uq_coach_seat')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('pnr_number', sa.String(length=10), nullable=False),
    sa.Column('qr_code_data', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_pnr_number'), 'tickets', ['pnr_number'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancellation_id', sa.Integer(), nullable=False),
    sa.Column('refund_reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cancellation_id'], ['cancellations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_reference'), 'refunds', ['refund_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_refund_reference'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_pnr_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_pnr_records_pnr_number'), table_name='pnr_records')
    op.drop_index(op.f('ix_pnr_records_id'), table_name='pnr_records')
    op.drop_table('pnr_records')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_cancellations_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_cancellation_reference'), table_name='cancellations')
    op.drop_table('cancellations')
    op.drop_index(op.f('ix_booking_passengers_id'), table_name='booking_passengers')
    op.drop_table('booking_passengers')
    op.drop_index(op.f('ix_train_stops_id'), table_name='train_stops')
    op.drop_table('train_stops')
    op.drop_index(op.f('ix_train_routes_id'), table_name='train_routes')
    op.drop_table('train_routes')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fares_id'), table_name='fares')
    op.drop_table('fares')
    op.drop_index(op.f('ix_coaches_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_bookings_journey_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_availability_journey_date'), table_name='availability')
    op.drop_index(op.f('ix_availability_id'), table_name='availability')
    op.drop_table('availability')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trains_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_name'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.drop_index(op.f('ix_stations_city'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_seat_classes_id'), table_name='seat_classes')
    op.drop_table('seat_classes')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_passengers_id'), table_name='passengers')
    op.drop_table('passengers')
    # ### end Alembic commands ###
